Description: "SnowFlake SageMaker Notebook"
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: SnowFlake SageMaker Notebook Configuration
        Parameters:
          - pSageMakerNotebookType
    ParameterLabels:
      pSageMakerNotebookType:
        default: SageMaker Notebook Type
      pNodeType:
        default: Node Instance Type
      pNumberOfNodes:
        default: Number of Compute Nodes
      pDBPortNumber:
        default: Listener Port
      pDatabaseName:
        default: Database Name
      pMasterUsername:
        default: DB User Name
      pMasterUserPassword:
        default: DB User Password
      pClusterSubnet:
        default: DB Cluster Subnet
      pDBSecurityGroups:
        default: DB Cluster Security Groups
Resources:
  SnowFlakeNotebookLifeCycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      OnCreate:
        - Content: !Base64 |
                #!/bin/bash
                set -e
                sudo -u ec2-user -i <<'EOF'
                        
                SUPPORTED_KERNELS=(tensorflow_p36 pytorch_p36 mxnet_p36 python3 amazonei_tensorflow_p36)

                for env in "${SUPPORTED_KERNELS[@]}";
                do
                    source /home/ec2-user/anaconda3/bin/activate "$env"
                    nohup pip install --upgrade snowflake-connector-python &
                    source /home/ec2-user/anaconda3/bin/deactivate
                done

                EOF
  SnowFlakeNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.t2.medium"
      RoleArn: !GetAtt ExecutionRole.Arn
      LifecycleConfigName: !GetAtt SnowFlakeNotebookLifeCycleConfig.NotebookInstanceLifecycleConfigName
  ExecutionRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "sagemaker.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "root"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"
Outputs:
  NotebookInstanceId:
    Value: !Ref SnowFlakeNotebookInstance